<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Content Remove="Properties\launchSettings.json" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Properties\launchSettings.json" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.9" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\LearningProject1.Core\LearningProject1.Core.csproj" />
    <ProjectReference Include="..\LearningProject1.DataLayer\LearningProject1.DataLayer.csproj" />
  </ItemGroup>

</Project>
